/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here

        //tests.testCase01();
        // SearchAmazon sa = new SearchAmazon();
        // sa.testCase01();
        
        // CountHyperlinks ch = new CountHyperlinks();
        // ch.testCase01();

        // Linkedin li = new Linkedin();
        // li.testCase01();

        // ImageUrls iu = new ImageUrls();
        // iu.testCase01();

        NestedFrames nf = new NestedFrames();
        nf.testCase01();

        // WindowHandle wh = new WindowHandle();
        // wh.testCase01();

        // ImdbRatings rating = new ImdbRatings();
        // rating.testCase01();

        //END Tests
        //sa.endTest();
        // ch.endTest();
        // li.endTest();
        // iu.endTest();
        nf.endTest();
        // wh.endTest();
        // rating.endTest();


        //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
